spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bank_build?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username:
    password:

