spring:
  datasource:
    url: jdbc:mysql://yingdiandian.mysql.rds.aliyuncs.com:3306/bank_build?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
    username: yingdd
    password: Yingdd2015

  redis:
    host: 127.0.0.1
    password: yingdiandian2015
    timeout: 6000
    port: 6379

  jpa:
    show-sql: true

server:
  port: 8887
