package com.ydd.oms.mapper.common;

import com.ydd.oms.entity.common.Region;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface RegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbg.generated Fri Sep 22 17:01:29 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbg.generated Fri Sep 22 17:01:29 CST 2017
     */
    int insert(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbg.generated Fri Sep 22 17:01:29 CST 2017
     */
    int insertSelective(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbg.generated Fri Sep 22 17:01:29 CST 2017
     */
    Region selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbg.generated Fri Sep 22 17:01:29 CST 2017
     */
    int updateByPrimaryKeySelective(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_region
     *
     * @mbg.generated Fri Sep 22 17:01:29 CST 2017
     */
    int updateByPrimaryKey(Region record);

    List<Region> selectByParentId(Integer parentId);

    /**
     * 查询上级编号
     *
     * @param ids 地区编号
     * @return 上级编号
     */
    Set<Integer> findParentIdSet(@Param("ids") Set<Integer> ids);

    /**
     * 更新地区开放状态
     *
     * @param ids 地区
     * @param openStatus 开放状态
     */
    void updateOpenStatus(@Param("ids") Set<Integer> ids,
                          @Param("openStatus") Byte openStatus);
}